// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1xpFk-pEVYsF2H4o5wOPevbDiS6TcQgM',
    appId: '1:655795631522:web:0e2ec984092c984e6aaefb',
    messagingSenderId: '655795631522',
    projectId: 'ecommerceproject-58328',
    authDomain: 'ecommerceproject-58328.firebaseapp.com',
    storageBucket: 'ecommerceproject-58328.firebasestorage.app',
    measurementId: 'G-CTKKZ20Q5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-ZaIY4Xp31gEisnegZ5qKxBeuldv3E54',
    appId: '1:655795631522:android:4e5e93aa1cd97ea56aaefb',
    messagingSenderId: '655795631522',
    projectId: 'ecommerceproject-58328',
    storageBucket: 'ecommerceproject-58328.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD59xEPnW_5DAlt18tnHc5H0LSN2UhCDWY',
    appId: '1:655795631522:ios:6e38768de8ab802e6aaefb',
    messagingSenderId: '655795631522',
    projectId: 'ecommerceproject-58328',
    storageBucket: 'ecommerceproject-58328.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );
}
